matrix:
  include:
    - sudo: required
      services:
        - docker
      language: bash
      before_script:
        - cd docker/mqtt
      script:
        # prepare qemu
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        # build image
        - docker build -t joengenduvel/mqtt .
        # test image
        #- docker run joengenduvel/mqtt mosquitto --version
        # push image
        - >
          if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
            docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
            TAG=$(grep "ENV MYSQL_VERSION" Dockerfile | awk 'NF>1{print $NF}')
            docker tag joengenduvel/mqtt joengenduvel/mqtt:$TAG
            docker push joengenduvel/mqtt:$TAG
            docker push joengenduvel/mqtt
          fi
