version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_POLL_INTERVAL: 900
  mqtt:
    image: joengenduvel/mqtt-armhf
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
  node-red:
    image: joengenduvel/node-red-armhf
    restart: unless-stopped
    ports:
      - "80:1880"
    depends-on:
      - "mqtt"
