apiVersion: v1
kind: Service
metadata:
  labels:
    app: mqtt
  name: mqtt
spec:
  ports:
  - name: "1883"
    port: 1883
    targetPort: 1883
  - name: "9001"
    port: 9001
    targetPort: 9001
  selector:
    app: mqtt
  type: LoadBalancer
  loadBalancerIP: 192.168.86.20
status:
  loadBalancer: {}
