apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mqtt
  name: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mqtt
    spec:
      containers:
      - image: eclipse-mosquitto
        name: mqtt
        ports:
        - containerPort: 1883
        - containerPort: 9001
        resources: {}
        volumeMounts:
        - name: config-volume
          mountPath: /mosquitto/config/
      restartPolicy: Always
      volumes:
      - name: config-volume
        configMap:
          # Provide the name of the ConfigMap containing the files you want
          # to add to the container
          name: mqtt-config
status: {}
