apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red
  labels:
    app: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
    spec:
      containers:
      - image: nodered/node-red
        name: node-red
        ports:
        - containerPort: 1880
      dnsPolicy: ClusterFirst
