apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-red
  name: node-red
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 1880
  selector:
    app: node-red
  type: LoadBalancer
  loadBalancerIP: 192.168.86.80
status:
  loadBalancer: {}
